apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: alert-notify
  namespace: cluster-config
spec:
  summary: "Flux events on the cluster"
  providerRef:
    name: test-webhook
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'