apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-configmap
  namespace: cluster-config
  labels:
    app: {{ template "hello-world.chart" . }}
data:
  myvalue: {{ index (index (lookup "v1" "Node" "" "").items 0).metadata.labels "kubernetes.azure.com/kubelet-identity-client-id" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-configmap2
  namespace: cluster-config
  labels:
    app: {{ template "hello-world.chart" . }}
data:
  myvalue: {{ index (index (lookup "v1" "Node" "" "").items 0).metadata.labels "kubernetes.azure.com/kubelet-identity-client-id" }}