apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: helloworld
  namespace: test-config
spec:
  interval: 1m
  approvePlan: auto
  path: ./terraform
  sourceRef:
    kind: GitRepository
    name: helloworld
    namespace: test-config