apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: cluster-config
spec:
  targetNamespace: nginx
  releaseName: nginx-ingress-controller
  chart:
    spec:
      chart: ./helmrepotest/nginx
      reconcileStrategy: ChartVersion
      valuesFiles:
      - ./values-patch.yaml
      sourceRef:
        kind: GitRepository
        name: cluster-config
        namespace: cluster-config
      #version: "9.x"
  interval: 1m2s
  install:
    remediation:
      retries: 3