apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-chart
  namespace: cluster-config
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: my-chart
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: acrrepo
      interval: 5m
  releaseName: my-chart
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    replicaCount: 1
