apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: acrrepo
  namespace: default
spec:
  interval: 1m0s
  type: oci
  url: oci://fluxtest.azurecr.io/helm
  provider: azure