apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: app1
  namespace: cluster-config
spec:
  imageRepositoryRef:
    name: podinfo
    namespace: cluster-config
  filterTags:
    extract: $version
    pattern: ^(?P<version>[0-9]+-[0-9]+)$
  policy:
    alphabetical:
      order: asc