apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: cluster-config
spec:
  values:
    image:
      repository: ghcr.io/stefanprodan/podinfo # {"$imagepolicy": "cluster-config:podinfo:name"}
      tag: 6.3.2  # {"$imagepolicy": "cluster-config:podinfo:tag"}