apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: keda
  namespace: ldl-da-aseuser-ns
spec:
  interval: 1m0s
  type: oci
  url: oci://fluxtest.azurecr.io/helm/timescaledb-single
  secretRef:
    name: ocicred