apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: ldl-da-aseuser-ns
spec:
  releaseName: keda
  chart:
    spec:
      chart: keda
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: ldl-da-aseuser-ns
  interval: 1h0m0s
  install:
    remediation:
      retries: 1